set nocompatible
set viminfo=
set encoding=utf-8
set backspace=2
set updatetime=300
set ttyfast
set switchbuf=useopen
set shortmess+=c
set signcolumn=number
set showmode
set showcmd
set nostartofline
set autowrite
set nobackup
set nowritebackup
set noswapfile
set nowrap
set ruler
set ts=2
set sw=2
set sts=2
set expandtab
set incsearch
set ignorecase
set smartcase
set nohlsearch

syntax off
set background=light
filetype plugin indent on
